// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package sqlc

import (
	"context"
)

const getCredentialByInstance = `-- name: GetCredentialByInstance :one
SELECT id, instance_id, kind, ciphertext, nonce, key_id, expires_at, needs_reauth, created_at, updated_at FROM credentials WHERE instance_id = ?
`

func (q *Queries) GetCredentialByInstance(ctx context.Context, instanceID string) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByInstance, instanceID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyID,
		&i.ExpiresAt,
		&i.NeedsReauth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentialsForRekey = `-- name: ListCredentialsForRekey :many
SELECT id, instance_id, kind, ciphertext, nonce, key_id, expires_at, needs_reauth, created_at, updated_at FROM credentials
WHERE key_id != ?
ORDER BY created_at
LIMIT ?
`

type ListCredentialsForRekeyParams struct {
	KeyID string
	Limit int64
}

// Rotation: find everything still sealed under an old master key.
func (q *Queries) ListCredentialsForRekey(ctx context.Context, arg ListCredentialsForRekeyParams) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, listCredentialsForRekey, arg.KeyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Kind,
			&i.Ciphertext,
			&i.Nonce,
			&i.KeyID,
			&i.ExpiresAt,
			&i.NeedsReauth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringCredentials = `-- name: ListExpiringCredentials :many
SELECT id, instance_id, kind, ciphertext, nonce, key_id, expires_at, needs_reauth, created_at, updated_at FROM credentials
WHERE expires_at IS NOT NULL
  AND expires_at < ?
  AND needs_reauth = 0
ORDER BY expires_at
LIMIT ?
`

type ListExpiringCredentialsParams struct {
	ExpiresAt *int64
	Limit     int64
}

// Proactive refresh, so a request does not pay for a token exchange.
func (q *Queries) ListExpiringCredentials(ctx context.Context, arg ListExpiringCredentialsParams) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringCredentials, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Kind,
			&i.Ciphertext,
			&i.Nonce,
			&i.KeyID,
			&i.ExpiresAt,
			&i.NeedsReauth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCredentialNeedsReauth = `-- name: MarkCredentialNeedsReauth :exec
UPDATE credentials
SET needs_reauth = 1, updated_at = ?
WHERE id = ?
`

type MarkCredentialNeedsReauthParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) MarkCredentialNeedsReauth(ctx context.Context, arg MarkCredentialNeedsReauthParams) error {
	_, err := q.db.ExecContext(ctx, markCredentialNeedsReauth, arg.UpdatedAt, arg.ID)
	return err
}

const upsertCredential = `-- name: UpsertCredential :one
INSERT INTO credentials (
    id, instance_id, kind, ciphertext, nonce, key_id,
    expires_at, needs_reauth, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?, ?)
ON CONFLICT (instance_id) DO UPDATE SET
    kind         = excluded.kind,
    ciphertext   = excluded.ciphertext,
    nonce        = excluded.nonce,
    key_id       = excluded.key_id,
    expires_at   = excluded.expires_at,
    needs_reauth = 0,
    updated_at   = excluded.updated_at
RETURNING id, instance_id, kind, ciphertext, nonce, key_id, expires_at, needs_reauth, created_at, updated_at
`

type UpsertCredentialParams struct {
	ID         string
	InstanceID string
	Kind       string
	Ciphertext []byte
	Nonce      []byte
	KeyID      string
	ExpiresAt  *int64
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, upsertCredential,
		arg.ID,
		arg.InstanceID,
		arg.Kind,
		arg.Ciphertext,
		arg.Nonce,
		arg.KeyID,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyID,
		&i.ExpiresAt,
		&i.NeedsReauth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
