// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instances.sql

package sqlc

import (
	"context"
)

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (
    id, user_id, integration_id, display_name, params, enabled, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, 1, ?, ?)
RETURNING id, user_id, integration_id, display_name, params, enabled, created_at, updated_at
`

type CreateInstanceParams struct {
	ID            string
	UserID        string
	IntegrationID string
	DisplayName   string
	Params        string
	CreatedAt     int64
	UpdatedAt     int64
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, createInstance,
		arg.ID,
		arg.UserID,
		arg.IntegrationID,
		arg.DisplayName,
		arg.Params,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IntegrationID,
		&i.DisplayName,
		&i.Params,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, subject, slug, email, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, subject, slug, email, created_at, updated_at
`

type CreateUserParams struct {
	ID        string
	Subject   string
	Slug      string
	Email     string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Subject,
		arg.Slug,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Slug,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :exec
DELETE FROM instances WHERE id = ?
`

func (q *Queries) DeleteInstance(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInstance, id)
	return err
}

const getInstanceParams = `-- name: GetInstanceParams :one
SELECT params FROM instances WHERE id = ?
`

func (q *Queries) GetInstanceParams(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getInstanceParams, id)
	var params string
	err := row.Scan(&params)
	return params, err
}

const getIntegrationBySlug = `-- name: GetIntegrationBySlug :one
SELECT id, slug, name, version, created_at FROM integrations WHERE slug = ?
`

func (q *Queries) GetIntegrationBySlug(ctx context.Context, slug string) (Integration, error) {
	row := q.db.QueryRowContext(ctx, getIntegrationBySlug, slug)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBySubject = `-- name: GetUserBySubject :one
SELECT id, subject, slug, email, created_at, updated_at FROM users WHERE subject = ?
`

func (q *Queries) GetUserBySubject(ctx context.Context, subject string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySubject, subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Slug,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstancesBySubject = `-- name: ListInstancesBySubject :many
SELECT
    i.id,
    i.display_name,
    i.params,
    i.enabled,
    g.slug AS integration_slug
FROM instances i
JOIN users u        ON u.id = i.user_id
JOIN integrations g ON g.id = i.integration_id
WHERE u.subject = ?
ORDER BY i.created_at
`

type ListInstancesBySubjectRow struct {
	ID              string
	DisplayName     string
	Params          string
	Enabled         int64
	IntegrationSlug string
}

func (q *Queries) ListInstancesBySubject(ctx context.Context, subject string) ([]ListInstancesBySubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listInstancesBySubject, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstancesBySubjectRow{}
	for rows.Next() {
		var i ListInstancesBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Params,
			&i.Enabled,
			&i.IntegrationSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveInstance = `-- name: ResolveInstance :one
SELECT
    i.id,
    i.display_name,
    i.params,
    u.subject   AS owner_subject,
    u.slug      AS user_slug,
    g.slug      AS integration_slug,
    g.version   AS integration_version
FROM instances i
JOIN users u        ON u.id = i.user_id
JOIN integrations g ON g.id = i.integration_id
WHERE i.id = ?
  AND u.slug = ?
  AND g.slug = ?
  AND i.enabled = 1
`

type ResolveInstanceParams struct {
	ID     string
	Slug   string
	Slug_2 string
}

type ResolveInstanceRow struct {
	ID                 string
	DisplayName        string
	Params             string
	OwnerSubject       string
	UserSlug           string
	IntegrationSlug    string
	IntegrationVersion string
}

// The routing hot path. The id is the primary key, but the user and
// integration slugs must also match: a correct id under the wrong path does not
// resolve, so the URL as a whole identifies the instance.
func (q *Queries) ResolveInstance(ctx context.Context, arg ResolveInstanceParams) (ResolveInstanceRow, error) {
	row := q.db.QueryRowContext(ctx, resolveInstance, arg.ID, arg.Slug, arg.Slug_2)
	var i ResolveInstanceRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Params,
		&i.OwnerSubject,
		&i.UserSlug,
		&i.IntegrationSlug,
		&i.IntegrationVersion,
	)
	return i, err
}

const setInstanceEnabled = `-- name: SetInstanceEnabled :exec
UPDATE instances SET enabled = ?, updated_at = ? WHERE id = ?
`

type SetInstanceEnabledParams struct {
	Enabled   int64
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetInstanceEnabled(ctx context.Context, arg SetInstanceEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setInstanceEnabled, arg.Enabled, arg.UpdatedAt, arg.ID)
	return err
}

const updateInstanceParams = `-- name: UpdateInstanceParams :exec
UPDATE instances SET params = ?, updated_at = ? WHERE id = ?
`

type UpdateInstanceParamsParams struct {
	Params    string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateInstanceParams(ctx context.Context, arg UpdateInstanceParamsParams) error {
	_, err := q.db.ExecContext(ctx, updateInstanceParams, arg.Params, arg.UpdatedAt, arg.ID)
	return err
}

const upsertIntegration = `-- name: UpsertIntegration :one
INSERT INTO integrations (id, slug, name, version, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (slug) DO UPDATE SET
    name    = excluded.name,
    version = excluded.version
RETURNING id, slug, name, version, created_at
`

type UpsertIntegrationParams struct {
	ID        string
	Slug      string
	Name      string
	Version   string
	CreatedAt int64
}

func (q *Queries) UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) (Integration, error) {
	row := q.db.QueryRowContext(ctx, upsertIntegration,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Version,
		arg.CreatedAt,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}
