// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Credential struct {
	ID          string
	InstanceID  string
	Kind        string
	Ciphertext  []byte
	Nonce       []byte
	KeyID       string
	ExpiresAt   *int64
	NeedsReauth int64
	CreatedAt   int64
	UpdatedAt   int64
}

type Instance struct {
	ID            string
	UserID        string
	IntegrationID string
	DisplayName   string
	Params        string
	Enabled       int64
	CreatedAt     int64
	UpdatedAt     int64
}

type Integration struct {
	ID        string
	Slug      string
	Name      string
	Version   string
	CreatedAt int64
}

type User struct {
	ID        string
	Subject   string
	Slug      string
	Email     string
	CreatedAt int64
	UpdatedAt int64
}
