// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteInstance(ctx context.Context, id string) error
	GetCredentialByInstance(ctx context.Context, instanceID string) (Credential, error)
	GetInstanceParams(ctx context.Context, id string) (string, error)
	GetIntegrationBySlug(ctx context.Context, slug string) (Integration, error)
	GetUserBySubject(ctx context.Context, subject string) (User, error)
	// Rotation: find everything still sealed under an old master key.
	ListCredentialsForRekey(ctx context.Context, arg ListCredentialsForRekeyParams) ([]Credential, error)
	// Proactive refresh, so a request does not pay for a token exchange.
	ListExpiringCredentials(ctx context.Context, arg ListExpiringCredentialsParams) ([]Credential, error)
	ListInstancesBySubject(ctx context.Context, subject string) ([]ListInstancesBySubjectRow, error)
	MarkCredentialNeedsReauth(ctx context.Context, arg MarkCredentialNeedsReauthParams) error
	// The routing hot path. The id is the primary key, but the user and
	// integration slugs must also match: a correct id under the wrong path does not
	// resolve, so the URL as a whole identifies the instance.
	ResolveInstance(ctx context.Context, arg ResolveInstanceParams) (ResolveInstanceRow, error)
	SetInstanceEnabled(ctx context.Context, arg SetInstanceEnabledParams) error
	UpdateInstanceParams(ctx context.Context, arg UpdateInstanceParamsParams) error
	UpsertCredential(ctx context.Context, arg UpsertCredentialParams) (Credential, error)
	UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) (Integration, error)
}

var _ Querier = (*Queries)(nil)
