// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package sqlc

import (
	"context"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (
    id, subject, name, hash, scoped, expires_at, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, subject, name, hash, expires_at, created_at, last_used_at, scoped
`

type CreateTokenParams struct {
	ID        string
	Subject   string
	Name      string
	Hash      string
	Scoped    int64
	ExpiresAt *int64
	CreatedAt int64
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.ID,
		arg.Subject,
		arg.Name,
		arg.Hash,
		arg.Scoped,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Name,
		&i.Hash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Scoped,
	)
	return i, err
}

const deleteToken = `-- name: DeleteToken :execrows
DELETE FROM tokens WHERE id = ? AND subject = ?
`

type DeleteTokenParams struct {
	ID      string
	Subject string
}

func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteToken, arg.ID, arg.Subject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, subject, name, hash, expires_at, created_at, last_used_at, scoped FROM tokens WHERE hash = ?
`

func (q *Queries) GetTokenByHash(ctx context.Context, hash string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByHash, hash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Name,
		&i.Hash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Scoped,
	)
	return i, err
}

const grantTokenInstance = `-- name: GrantTokenInstance :exec
INSERT INTO token_grants (token_id, instance_id) VALUES (?, ?)
`

type GrantTokenInstanceParams struct {
	TokenID    string
	InstanceID string
}

func (q *Queries) GrantTokenInstance(ctx context.Context, arg GrantTokenInstanceParams) error {
	_, err := q.db.ExecContext(ctx, grantTokenInstance, arg.TokenID, arg.InstanceID)
	return err
}

const listGrantsForSubject = `-- name: ListGrantsForSubject :many
SELECT
    token_grants.token_id,
    token_grants.instance_id,
    instances.display_name AS instance_name,
    integrations.slug      AS integration_slug
FROM token_grants
JOIN tokens       ON tokens.id = token_grants.token_id
JOIN instances    ON instances.id = token_grants.instance_id
JOIN integrations ON integrations.id = instances.integration_id
WHERE tokens.subject = ?
`

type ListGrantsForSubjectRow struct {
	TokenID         string
	InstanceID      string
	InstanceName    string
	IntegrationSlug string
}

// Every grant belonging to a subject's tokens, so a listing can name the
// endpoints each token reaches without a query per token.
func (q *Queries) ListGrantsForSubject(ctx context.Context, subject string) ([]ListGrantsForSubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listGrantsForSubject, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantsForSubjectRow{}
	for rows.Next() {
		var i ListGrantsForSubjectRow
		if err := rows.Scan(
			&i.TokenID,
			&i.InstanceID,
			&i.InstanceName,
			&i.IntegrationSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensForSubject = `-- name: ListTokensForSubject :many
SELECT id, subject, name, hash, expires_at, created_at, last_used_at, scoped FROM tokens WHERE subject = ? ORDER BY created_at DESC
`

func (q *Queries) ListTokensForSubject(ctx context.Context, subject string) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listTokensForSubject, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Name,
			&i.Hash,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Scoped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tokenGrantsInstance = `-- name: TokenGrantsInstance :one
SELECT COUNT(*) FROM token_grants WHERE token_id = ? AND instance_id = ?
`

type TokenGrantsInstanceParams struct {
	TokenID    string
	InstanceID string
}

// Whether a scoped token names this instance. Unscoped tokens never reach here.
func (q *Queries) TokenGrantsInstance(ctx context.Context, arg TokenGrantsInstanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, tokenGrantsInstance, arg.TokenID, arg.InstanceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const touchToken = `-- name: TouchToken :exec
UPDATE tokens
SET last_used_at = ?
WHERE id = ? AND (last_used_at IS NULL OR last_used_at < ?)
`

type TouchTokenParams struct {
	LastUsedAt   *int64
	ID           string
	LastUsedAt_2 *int64
}

// Skips the write unless a minute has passed, so a token in constant use does
// not serialise every request behind a write on a single-writer database.
func (q *Queries) TouchToken(ctx context.Context, arg TouchTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchToken, arg.LastUsedAt, arg.ID, arg.LastUsedAt_2)
	return err
}
